### ISSUE TITLE
Google *does* support OOB?

### ISSUE THREAD

**Issue by allentiak** [hhru/subscribe#11]
Hello,

Are you sure Google does still not support OOB?

When creating a client ID in the Developers Console (console.developers.google.com/project/<my-project>/apiui/credential) there no blank URI option...

For the specific case of a new client ID (of type "Installed application -> Other"), the default options are:
- urn:ietf:wg:oauth:2.0:oob
- http://localhost

Best,
Leandro

**Comment by kullfar** [comment]
sorry, have missed your issue.
But I didn't catch the hint ;-)
What is bad with subscribe? How can it be improved?
